/* Generated By:JavaCC: Do not edit this line. ZaraParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ZaraParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 1;
  /** RegularExpression Id. */
  int CONSTANT = 2;
  /** RegularExpression Id. */
  int FLOAT = 3;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int LETTER = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"IDENTIFIER\"",
    "\"CONSTANT\"",
    "\"FLOAT\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"return\"",
    "\"||\"",
    "\"&&\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<DIGIT>",
    "<LETTER>",
  };

}
