/* Generated By:JavaCC: Do not edit this line. ZaraParserConstants.java */
package red.stevo.code.Lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ZaraParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 1;
  /** RegularExpression Id. */
  int ELSE = 2;
  /** RegularExpression Id. */
  int WHILE = 3;
  /** RegularExpression Id. */
  int FOR = 4;
  /** RegularExpression Id. */
  int RETURN = 5;
  /** RegularExpression Id. */
  int CONST = 6;
  /** RegularExpression Id. */
  int GLOB = 7;
  /** RegularExpression Id. */
  int IN = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int ARRAY = 10;
  /** RegularExpression Id. */
  int STACK = 11;
  /** RegularExpression Id. */
  int ELSE_IF = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int CONTINUE = 14;
  /** RegularExpression Id. */
  int CLASS = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int GT = 19;
  /** RegularExpression Id. */
  int LT = 20;
  /** RegularExpression Id. */
  int GTE = 21;
  /** RegularExpression Id. */
  int LTE = 22;
  /** RegularExpression Id. */
  int PLUS = 23;
  /** RegularExpression Id. */
  int MINUS = 24;
  /** RegularExpression Id. */
  int MULT = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int NOT = 28;
  /** RegularExpression Id. */
  int DOT = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int LPAREN = 31;
  /** RegularExpression Id. */
  int RPAREN = 32;
  /** RegularExpression Id. */
  int LBRACE = 33;
  /** RegularExpression Id. */
  int RBRACE = 34;
  /** RegularExpression Id. */
  int SEMICOLON = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int COLON = 37;
  /** RegularExpression Id. */
  int LSQUARE = 38;
  /** RegularExpression Id. */
  int RSQUARE = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;
  /** RegularExpression Id. */
  int CONSTANT = 41;
  /** RegularExpression Id. */
  int FLOAT = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;
  /** RegularExpression Id. */
  int LETTER = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"return\"",
    "\"const\"",
    "\"global\"",
    "\"in\"",
    "\"string\"",
    "\"arr\"",
    "\"stack\"",
    "\"else-if\"",
    "\"do\"",
    "\"continue\"",
    "\"class\"",
    "\"int\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"!\"",
    "\".\"",
    "\"||\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "<IDENTIFIER>",
    "<CONSTANT>",
    "<FLOAT>",
    "<DIGIT>",
    "<LETTER>",
    "\"!=\"",
  };

}
