
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package red.stevo.code.Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OPERATOR_DOT = 17;
  public static final int OPERATOR_MUL = 7;
  public static final int CONSTANT = 3;
  public static final int OPERATOR_EQUAL = 18;
  public static final int IDENTIFIER = 2;
  public static final int OPERATOR_LESS_EQUAL = 14;
  public static final int SEMI_COLON = 25;
  public static final int OPERATOR_AND = 12;
  public static final int PUNCTUATION_CURLED_RIGHT = 20;
  public static final int OPERATOR_GREATER_EQUAL = 13;
  public static final int KEYWORD = 28;
  public static final int PUNCTUATION_COLON = 22;
  public static final int FLOAT = 4;
  public static final int OPERATOR_NOT = 15;
  public static final int EOF = 0;
  public static final int PUNCTUATION_RIGHT = 27;
  public static final int PUNCTUATION_CURLED_LEFT = 19;
  public static final int PUNCTUATION_SQUARE_LEFT = 23;
  public static final int OPERATOR_GREATER = 10;
  public static final int OPERATOR_LESS = 11;
  public static final int PUNCTUATION_COMMA = 21;
  public static final int error = 1;
  public static final int OPERATOR_SUB = 6;
  public static final int PUNCTUATION_SQUARE_RIGHT = 24;
  public static final int ASSIGN = 9;
  public static final int PUNCTUATION_LEFT = 26;
  public static final int OPERATOR_DIV = 8;
  public static final int OPERATOR_OR = 16;
  public static final int OPERATOR_ADD = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "CONSTANT",
  "FLOAT",
  "OPERATOR_ADD",
  "OPERATOR_SUB",
  "OPERATOR_MUL",
  "OPERATOR_DIV",
  "ASSIGN",
  "OPERATOR_GREATER",
  "OPERATOR_LESS",
  "OPERATOR_AND",
  "OPERATOR_GREATER_EQUAL",
  "OPERATOR_LESS_EQUAL",
  "OPERATOR_NOT",
  "OPERATOR_OR",
  "OPERATOR_DOT",
  "OPERATOR_EQUAL",
  "PUNCTUATION_CURLED_LEFT",
  "PUNCTUATION_CURLED_RIGHT",
  "PUNCTUATION_COMMA",
  "PUNCTUATION_COLON",
  "PUNCTUATION_SQUARE_LEFT",
  "PUNCTUATION_SQUARE_RIGHT",
  "SEMI_COLON",
  "PUNCTUATION_LEFT",
  "PUNCTUATION_RIGHT",
  "KEYWORD"
  };
}

