
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package red.stevo.code.Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CONSTANT = 3;
  public static final int SEMI_COLON = 10;
  public static final int PUNCTUATION_LEFT = 11;
  public static final int EOF = 0;
  public static final int OPERATOR_ADD = 5;
  public static final int ASSIGN = 9;
  public static final int error = 1;
  public static final int OPERATOR_SUB = 6;
  public static final int OPERATOR_DIV = 8;
  public static final int IDENTIFIER = 2;
  public static final int PUNCTUATION_RIGHT = 12;
  public static final int KEYWORD = 13;
  public static final int FLOAT = 4;
  public static final int OPERATOR_MUL = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "CONSTANT",
  "FLOAT",
  "OPERATOR_ADD",
  "OPERATOR_SUB",
  "OPERATOR_MUL",
  "OPERATOR_DIV",
  "ASSIGN",
  "SEMI_COLON",
  "PUNCTUATION_LEFT",
  "PUNCTUATION_RIGHT",
  "KEYWORD"
  };
}

